lib/detective_web/router.ex
defmodule DetectiveWeb.Router do
  use DetectiveWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DetectiveWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/street_reports", StreetReportController, only: [:index, :show]
  end
end

lib/detective/application.ex
defmodule Detective.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Detective.Repo, []),
      # Start the endpoint when the application starts
      supervisor(DetectiveWeb.Endpoint, []),
      # Start your own worker by calling: Detective.Worker.start_link(arg1, arg2, arg3)
      # worker(Detective.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Detective.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    DetectiveWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/detective/repo.ex
defmodule Detective.Repo do
  use Ecto.Repo, otp_app: :detective
  use Scrivener, page_size: 15

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/detective/reports/reports.ex
defmodule Detective.Reports do
  @moduledoc """
  The Reports context.
  """

  import Ecto.Query, warn: false
  alias Detective.Repo

  alias Detective.Reports.StreetReport

  @doc """
  Returns the list of street_reports.

  ## Examples

      iex> list_street_reports()
      [%StreetReport{}, ...]

  """
  def list_street_reports do
    Repo.all(StreetReport)
  end

  @doc """
  Returns query that compose sort and filter queries.

  Returns StreetReport module if the params are empty Map.

  ## Examples

      iex> filtered_and_sort_query_street_reports(%{})
      StreetReport

      iex> filtered_and_sort_query_street_reports(%{sort: "id"})
      %Ecto.Query{}

  """
  def filtered_and_sort_query_street_reports(params) do
    StreetReport
    |> query_sort_by(params[:sort])
    |> query_filter_by(params[:filters])
  end

  @doc """
  Gets a single street_report.

  Raises `Ecto.NoResultsError` if the Street report does not exist.

  ## Examples

      iex> get_street_report!(123)
      %StreetReport{}

      iex> get_street_report!(456)
      ** (Ecto.NoResultsError)

  """
  def get_street_report!(id), do: Repo.get!(StreetReport, id)

  @doc """
  Creates a street_report.

  ## Examples

      iex> create_street_report(%{field: value})
      {:ok, %StreetReport{}}

      iex> create_street_report(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_street_report(attrs \\ %{}) do
    %StreetReport{}
    |> StreetReport.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking street_report changes.

  ## Examples

      iex> change_street_report(street_report)
      %Ecto.Changeset{source: %StreetReport{}}

  """
  def change_street_report(%StreetReport{} = street_report) do
    StreetReport.changeset(street_report, %{})
  end

  defp query_sort_by(query, sort) when is_nil(sort), do: query
  defp query_sort_by(query, sort) when is_binary(sort) do
    query |> order_by(desc: ^String.to_atom(sort))
  end

  defp query_filter_by(query, filters) when is_nil(filters), do: query
  defp query_filter_by(query, filters) do
    Enum.reduce(filters, query, fn({filter, value}, query) ->
      case String.downcase(filter) do
        "crime_type" ->
          from p in query,
          where: ilike(p.crime_type, ^("%#{value}%"))
        _ ->
          from p in query,
          where: field(p, ^String.to_atom(filter)) == ^value
      end
    end)
  end
end

lib/detective/reports/street_report.ex
defmodule Detective.Reports.StreetReport do
  use Ecto.Schema
  import Ecto.Changeset

  schema "street_reports" do
    field :context, :string
    field :crime_id, :string
    field :crime_type, :string
    field :falls_within, :string
    field :last_outcome_category, :string
    field :latitude, :float
    field :location, :string
    field :longitude, :float
    field :lsoa_code, :string
    field :lsoa_name, :string
    field :month, :string
    field :reported_by, :string

    timestamps()
  end

  @doc false
  def changeset(street_report, attrs) do
    street_report
    |> cast(attrs, [:crime_id, :month, :reported_by, :falls_within, :longitude, :latitude, :location, :lsoa_code, :lsoa_name, :crime_type, :last_outcome_category, :context])
    |> validate_required([:crime_id, :month, :reported_by, :crime_type])
  end
end

lib/mix/tasks/detective.import_report.ex
defmodule Mix.Tasks.Detective.ImportStreetReport do
  use Mix.Task

  require CSV
  require Logger

  alias Detective.Reports

  @shortdoc "Imports into the database police report file"
  def run(path) do
    run_app_start_task

    path
    |> Path.expand(File.cwd!)
    |> File.stream!([:read])
    |> CSV.decode(headers: true)
    |> Enum.map(&import_record/1)
  end

  defp run_app_start_task do
    Mix.Task.run "app.start"
  end

  defp import_record({:ok, record}) do
    with {:ok, _changeset} <- create_street_report(record) do
      :ok
    else
      {:error, changeset} ->
        changeset.errors
        |> Enum.map_join(", ", fn {field, {message, _}} -> "#{field}: #{message}" end)
        |> Logger.warn()
    end
  end

  defp import_record({:error, reason}), do: Logger.warn(reason)

  defp create_street_report(record) do
    Reports.create_street_report(%{
      context: record["context"],
      crime_id: record["crime_id"],
      crime_type: record["crime_type"],
      falls_within: record["falls_within"],
      last_outcome_category: record["last_outcome_category"],
      latitude: record["latitude"],
      location: record["location"],
      longitude: record["longitude"],
      lsoa_code: record["lsoa_code"],
      lsoa_name: record["lsoa_name"],
      month: record["month"],
      reported_by: record["reported_by"]
    })
  end
end

lib/detective_web/controllers/page_controller.ex
defmodule DetectiveWeb.PageController do
  use DetectiveWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/detective_web/controllers/street_report_controller.ex
defmodule DetectiveWeb.StreetReportController do
  use DetectiveWeb, :controller
  import DetectiveWeb.Plugs.Filters
  alias Detective.Reports

  plug(:allowed_filters, ~w(crime_type) when action in [:index])

  def index(conn, params) do
    query = Reports.filtered_and_sort_query_street_reports(%{filters: conn.assigns.filters, sort: params["sort"] })
    page = Detective.Repo.paginate(query, params)

    render(conn, "index.html", street_reports: page.entries, page: page, sort: params["sort"])
  end

  def show(conn, %{"id" => id}) do
    street_report = Reports.get_street_report!(id)

    render(conn, "show.html", street_report: street_report)
  end
end

lib/detective_web/views/error_view.ex
defmodule DetectiveWeb.ErrorView do
  use DetectiveWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/detective_web/views/layout_view.ex
defmodule DetectiveWeb.LayoutView do
  use DetectiveWeb, :view
end

lib/detective_web/views/page_view.ex
defmodule DetectiveWeb.PageView do
  use DetectiveWeb, :view
end

lib/detective_web/views/street_report_view.ex
defmodule DetectiveWeb.StreetReportView do
  use DetectiveWeb, :view
  import Scrivener.HTML
end

lib/detective_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Detective!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="/">Reports</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/detective_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Scotland Yard Reports" %></h2>
</div>

<div class="row marketing">
  <div class="col-lg-12">
    <h4>Reports</h4>
    <ul>
      <li>
        <%= link "Street crimes", to: street_report_path(@conn, :index) %>
      </li>
    </ul>
  </div>
</div>

lib/detective_web/templates/street_report/index.html.eex
<div class="row marketing">
  <div class="col-lg-12">
    <div class="form">
      <%= form_for @conn, street_report_path(@conn, :index), [method: :get, as: :filters], fn f -> %>
        <label>
          Crime Type <%= text_input f, :crime_type %>
        </label>
        <%= submit "Filter" %>
      <% end %>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th><%= link "Id", to: street_report_path(@conn, :index, sort: "id", filters: @filters) %> </th>
          <th><%= link "Crime Type", to: street_report_path(@conn, :index, sort: "crime_type", filters: @filters) %> </th>
          <th><%= link "Location", to: street_report_path(@conn, :index, sort: "location", filters: @filters) %> </th>
          <th><%= link "Outcome", to: street_report_path(@conn, :index, sort: "last_outcome_category", filters: @filters) %> </th>
          <th><%= link "Month", to: street_report_path(@conn, :index, sort: "month", filters: @filters) %> </th>
        </tr>
      </thead>
      <tbody>
        <%= for report <- @street_reports do %>
          <tr>
            <td><%= link "#{report.id}", to: street_report_path(@conn, :show, report) %></td>
            <td><%= report.crime_type %></td>
            <td><%= report.location %></td>
            <td><%= report.last_outcome_category %></td>
            <td><%= report.month %></td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <%= if is_nil(@sort) do %>
          <%= pagination_links(@page, filters: @filters) %>
        <% else %>
          <%= pagination_links(@page, sort: @sort, filters: @filters) %>
        <% end %>
      </tfoot>
    </table>
  </div>
</div>

lib/detective_web/templates/street_report/show.html.eex
<div class="row marketing">
  <div class="col-lg-12">
    <h2>Show Street Report</h2>
    <ul class="report">
        <li>
          <strong>Id:</strong>
          <%= @street_report.id %>
        </li>
        <li>
          <strong>Crime Id:</strong>
          <%= @street_report.crime_id %>
        </li>
        <li>
          <strong>Crime Type:</strong>
          <%= @street_report.crime_type %>
        </li>
        <li>
          <strong>Reported By:</strong>
          <%= @street_report.reported_by %>
        </li>
        <li>
          <strong>Location:</strong>
          <%= @street_report.location %>
        </li>
        <li>
          <strong>Longitude:</strong>
          <%= @street_report.longitude %>
        </li>
        <li>
          <strong>Latitude:</strong>
          <%= @street_report.latitude %>
        </li>
        <li>
          <strong>Outcome Category:</strong>
          <%= @street_report.last_outcome_category %>
        </li>
        <li>
          <strong>Context:</strong>
          <%= @street_report.context%>
        </li>
        <li>
          <strong>LSOA Code:</strong>
          <%= @street_report.lsoa_code %>
        </li>
        <li>
          <strong>LSOA Name:</strong>
          <%= @street_report.lsoa_name %>
        </li>
    </ul>
  </div>
</div>